FROM cnstark/pytorch:2.0.0-py3.9.12-cuda11.8.0-ubuntu22.04

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /workspace

#RUN pip install PyYAML==5.4.1 numpy==1.20.2 matplotlib==3.4.2 scipy==1.10.1 scikit-learn==0.24.2 pandas==1.2.5 Pillow==8.2.0
RUN pip install PyYAML==5.4.1 numpy==1.20.2 matplotlib==3.4.2 scipy==1.10.1 scikit-learn==0.24.2 pandas==1.2.5 Pillow==8.2.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
