
dataset:
  name: enron
  folder: ./data/enron/
  edges_file: ml_enron.csv
  features_file: []
  aggr_time: 2592000
  steps_accounted: None

use_cuda: True
use_log: True
model: gcn_man
task: link_pred
class_weights: [0.1, 0.9]
use_2_hot_node_feats: False
use_1_hot_node_feats: True
save_node_embeddings: False
train_proportion: 0.700000
dev_proportion: 0.100000
num_epochs: 200
steps_accum_gradients: 1
learning_rate: 0.001000
negative_mult_training: 100
negative_mult_test: 100
smart_neg_sampling: True
target_measure: MAP
target_class: 1
early_stop_patience: 50
eval_after_epochs: 5
adj_mat_time_window: 1  # Time window to create the adj matrix for each timestep. Use None to use all the history (from 0 to t)
num_hist_steps: 5
seed: 1234

gcn_parameters:
  num_hidden_layers: 4
  hidden_feats: [128, 128, 128, 128]
  l1_weight: [0,0,80,80]
  l2_weight: [0,0,80,80]
  cls_feats: 100

data_loading_params:
  batch_size: 1
  num_workers: 8

log:
  folder: ./blog/enron/
  file: dataset=enron,task=link_pred,model=gcn_man.log

comments: 
  - comments
