
dataset:
  name: email_eu_dept1
  folder: ./data/email/
  edges_file: email-Eu-core-temporal-Dept1.txt
  aggr_time: 604800
  steps_accounted: 70

use_cuda: True
use_log: True
model: gcn_man
task: link_pred
class_weights: [0.1, 0.9]
use_2_hot_node_feats: False
use_1_hot_node_feats: True
save_node_embeddings: False
train_proportion: 0.700000
dev_proportion: 0.100000
num_epochs: 300    #number of passes though the data
steps_accum_gradients: 1
learning_rate: 0.001000
negative_mult_training: 100
negative_mult_test: 100
smart_neg_sampling: True
seed: 1234
target_measure: MAP
target_class: 1
early_stop_patience: 50
eval_after_epochs: 5
adj_mat_time_window: 1  # Time window to create the adj matrix for each timestep. Use None to use all the history (from 0 to t)
num_hist_steps: 5

gcn_parameters:
  num_hidden_layers: 20
  hidden_feats: [64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64]
  l1_weight: [0,0,50,50]
  l2_weight: [0,0,50,50]
  cls_feats: 100  # Hidden size of the classifier

data_loading_params:
  batch_size: 1
  num_workers: 8

log:
  folder: ./blog/email_eu_dept1/
  file: dataset=email_eu_dept1,task=link_pred,model=gcn_man.log

comments: 
  - comments
